spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: mysql://${{ MYSQLUSER }}:${{ MYSQLPASSWORD }}@${{ MYSQLHOST }}:${{ MYSQLPORT }}/${{ MYSQLDATABASE }}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true